---
title: "JASA_simulations"
author: "Ziyi Wang"
date: "2026-02-07"
output: html_document
---
## Load Packages/Functions

```{r setup, include=FALSE}
library(knitr)
library(locfdr)
library(CATMicrobiome)
library(admix)
library(mvtnorm)
library(mixtools)
library(devtools)
library(KScorrect)
library(mclust)
library(adaptMT)
library(AdaPTGMM)
library(splines2)
library(splines)
library(dplyr)
library(ggplot2)
library(tidyr)
library(coin)
library(ggrepel)
library(viridisLite)
library(IHW)
library(FDRreg)
library(OrderShapeEM)

devtools::load_all("C:/Ziyi Wang/chai_package/chai")
```

## Simulations
### Simulation 1 - One dimensional x 
sim a

```{r setup, include=FALSE}
run_all_methods_sim <- function(seed, a_val, q_grid, 
                                n0 = 950,  n1 = 25,   n2 = 25,
                                m0 = 0,    m1 = 2,    m2 = -4,
                                sd0 = 1,   sd1 = 1,   sd2 = 1){
  set.seed(seed)
  
  # Simulation generation - z
  n <- n0 + n1 + n2
  z0 <- rnorm(n0, mean = 0, sd = 1)
  z1 <- rnorm(n1, mean = 2, sd = 0.5)
  z2 <- rnorm(n2, mean = -2, sd = 0.5)
  z  <- c(z0, z1, z2)
  # gt <- seq((n0 + 1), n)
  p <- 2 * (1 - pnorm(abs(z)))
  
  # Simulation generation - X
  m0a <- m0
  m1a <- m0 + a_val * (m1 - m0)
  m2a <- m0 + a_val * (m2 - m0)
  
  x0 <- rnorm(n0, mean = m0a, sd = sd0)
  x1 <- rnorm(n1, mean = m1a, sd = sd1)
  x2 <- rnorm(n2, mean = m2a, sd = sd2)
  X  <- c(x0, x1, x2)
  x_df <- data.frame(X = X)
  formula <- paste0("ns(X, df = ", 2:8, ")")
  
  # Initialize a list
  run_results <- list()
  
  ## 1) chai 
  res_chai <- chai(z, X, B = 100)
  
  for (qq in seq_along(q_grid)) {
    select <- clfdrselect(res_chai, q = q_grid[qq])
    p1  <- performance(gt, select, z = res_chai$z,
                       bh_level = q_grid[qq], one.sided = FALSE)
    # chai
    run_results[[length(run_results)+1]] <- 
       data.frame(Seed = seed, a = a_val, 
                  q = q_grid[qq], Method = "chai", 
                  Selected = p1[[4]], FDP = p1[[1]], Power = p1[[2]])
    # BH
    run_results[[length(run_results)+1]] <- 
       data.frame(Seed = seed, a = a_val, 
                  q = q_grid[qq], Method = "BH", 
                  Selected = p1[[13]], FDP = p1[[8]], Power = p1[[9]])
  }

  ## 2) adapt_gmm (z)
  res_gmm_z <- adapt_gmm(x_df, z = z, alphas = q_grid,
                         beta_formulas = formula, testing = "two_sided")
  
  for (qq in seq_along(q_grid)) {
    p2  <- performance(gt, res_gmm_z$rejs[[qq]], z = z,
                       bh_level = q_grid[qq], one.sided = FALSE)
    run_results[[length(run_results)+1]] <- 
       data.frame(Seed = seed, a = a_val, 
                  q = q_grid[qq], Method = "adapt_gmm_z", 
                  Selected = p2[[4]], FDP = p2[[1]], Power = p2[[2]])
  }

  ## 3) adapt_gmm (p)
  res_gmm_p <- adapt_gmm(x_df, pvals = p, alphas = q_grid,
                         beta_formulas = formula, testing = "two_sided")
  for (qq in seq_along(q_grid)) {
    # idx <- match(qq, q_grid)
    p3  <- performance(gt, res_gmm_p$rejs[[qq]], z = z,
                       bh_level = q_grid[qq], one.sided = FALSE)
    run_results[[length(run_results)+1]] <- 
       data.frame(Seed = seed, a = a_val, 
                  q = q_grid[qq], Method = "adapt_gmm_p", 
                  Selected = p3[[4]], FDP = p3[[1]], Power = p3[[2]])
  }

  ## 4) adapt_glm
  res_glm <- adapt_glm(x_df, pvals = p, alphas = q_grid,
                       pi_formulas = formula, mu_formulas = formula)
  empty <- is.null(res_glm) || (!is.list(res_glm$rejs))
  for (qq in seq_along(q_grid)) {
    if (!empty && lengths(res_glm$rejs)[qq] > 0L){
     p4 <- performance(gt, res_glm$rejs[[qq]], z = z,
                        bh_level = q_grid[qq], one.sided = FALSE)
     run_results[[length(run_results)+1]] <- 
       data.frame(Seed = seed, a = a_val, 
                  q = q_grid[qq], Method = "adapt_glm", 
                  Selected = p4[[4]], FDP = p4[[1]], Power = p4[[2]])
    } else {
      run_results[[length(run_results)+1]] <- 
       data.frame(Seed = seed, a = a_val, 
                  q = q_grid[qq], Method = "adapt_glm", 
                  Selected = 0, FDP = NA, Power = NA)
      }
  }

  ## 5) OrderShapeEM
  tryCatch({
    res_osem <- OrderShapeEM(pvals = p, order.var = X,
                             OrderShapeEM.control(trace = FALSE))
    for (qq in seq_along(q_grid)) {
      p5 <- performance(gt, which(res_osem$fdr <= q_grid[qq]), z = z,
                        bh_level = q_grid[qq], one.sided = FALSE)
      run_results[[length(run_results)+1]] <- 
       data.frame(Seed = seed, a = a_val, 
                  q = q_grid[qq], Method = "OrderShapeEM", 
                  Selected = p5[[4]], FDP = p5[[1]], Power = p5[[2]])
    }
  }, error = function(e) {
    message(paste("OrderShapeEM failed at seed", seeds[s], "a =", a, ":", e$message))
    for (qq in seq_along(q_grid)) {
      run_results[[length(run_results)+1]] <- 
       data.frame(Seed = seed, a = a_val, 
                  q = q_grid[qq], Method = "OrderShapeEM", 
                  Selected = NA, FDP = NA, Power = NA)
    }
  })

  ## 6) FDRreg（theoretical null）
  res_fdrreg <- FDRreg(z, as.matrix(X), nulltype = "theoretical")
  for (qq in seq_along(q_grid)) {
    p6 <- performance(gt, which(res_fdrreg$FDR <= q_grid[qq]), z = z,
                      bh_level = q_grid[qq], one.sided = FALSE)
    run_results[[length(run_results)+1]] <- 
       data.frame(Seed = seed, a = a_val, 
                  q = q_grid[qq], Method = "FDRreg", 
                  Selected = p6[[4]], FDP = p6[[1]], Power = p6[[2]])
  }
    
    
  ## 7) IHW
  for (qq in seq_along(q_grid)) {
    res_ihw <- IHW::ihw(pvalues = p, covariates = x_df[,1], alpha = q_grid[qq], nbins = 5)
    p7 <- performance(gt, which(IHW::adj_pvalues(res_ihw) <= q_grid[qq]), z = z, bh_level = qq, one.sided = FALSE)
    
    run_results[[length(run_results)+1]] <- 
       data.frame(Seed = seed, a = a_val, 
                  q = q_grid[qq], Method = "IHW", 
                  Selected = p7[[4]], FDP = p7[[1]], Power = p7[[2]])
  }
  
  # Clean up memory after this specific a_val/seed is done
  gc()
  
  return(do.call(rbind, run_results))
}

set.seed(1)
seeds <- c(sample(1:10000, 99), 123)

n  <- 1000
n0 <- 950
n1 <- 25
m0 <- 0; m1 <- 2; m2 <- -4
sd0 <- 1;   sd1 <- 1; sd2 <- 1

# ground truth
gt <- seq((n0 + 1), n)
  
# informativeness grid：from 'no info' to 'higher info'
a_grid <- c(0, 0.5, 1, 1.5, 2)
q_grid <- seq(0.01, 0.1, by = 0.01)

cache_file <- "all_methods_simulation_1_results.rds"

if (file.exists(cache_file)){
  # if already did, load it
  results_all <- readRDS(cache_file)
} else {
  # if not, run the simulation
  param_grid <- expand.grid(seed = seeds, a = a_grid)
  
  library(purrr)
  results_list <- pmap(list(param_grid$seed, param_grid$a),
                       ~run_all_methods_sim(seed = ..1, a_val = ..2, q_grid = q_grid))
  
  results_all <- bind_rows(results_list) %>% mutate(across(c(Selected, FDP, Power), as.numeric))
  
  # save to dist
  saveRDS(results_all, cache_file)
}
```
